language: haskell
env:
 - CABALVER=1.22 GHCVER=7.10.2
before_install:
  - export PATH=/opt/ghc/7.10.2/bin:$PATH
addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.2
install: cabal update
script: ./script.sh

